config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "flats#index"
  get "flats/:id", to: "flats#show", as: "flat"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  before_action :set_flats

  def index
  end

  def show
    @flat = @flats.find{ |flat| flat["id"] == params["id"].to_i }
  end

  private

  def set_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    json_response = URI.parse(url).read
    @flats = JSON.parse(json_response)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>

<ul>
  <% @flats.each do |flat| %>
    <li>
      <h2><%= link_to flat["name"], flat_path(flat["id"]) %></h2>
      <p><%= flat["price"] %> <%= flat["priceCurrency"] %></p>
    </li>
  <% end %>
</ul>

app/views/flats/show.html.erb
<h1><%= @flat["name"] %></h1>

<h2><%= @flat["price"] %> <%= @flat["priceCurrency"] %></h2>
<%= image_tag @flat["imageUrl"], width: 600 %>

<%= link_to "back to list", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>